baseURL = 'https://blog.pedropiveta.com.br/'
languageCode = 'pt-BR'
title = 'Blog Pedro Piveta'
theme = 'terminal'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    showMenuItems = 2
    fullWidthTheme = false
    centerTheme = false
    autoCover = true
    
    [params.twitter]
        creator = "PedroPiBarrotti"
        site = "PedroPiBarrotti"

    [params.logo]
        logoText = "Blog Pedro Piveta"

